name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Remplacez par la version souhaitée

      - name: Build and Test
        run: |
          dotnet build
          dotnet test

      - name: Publish
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true
        artifacts:
          paths:
            - ./path/to/published/executable

